// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFQmimrSANAewaZZMP4qaI2mFHTgU9rko',
    appId: '1:1042031045023:web:c5d3bb799a79939bb7b5aa',
    messagingSenderId: '1042031045023',
    projectId: 'roadsafety-f3755',
    authDomain: 'roadsafety-f3755.firebaseapp.com',
    storageBucket: 'roadsafety-f3755.appspot.com',
    measurementId: 'G-1GKLNCC2DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7f86Bngxl4r_LksBJZEXnnTWtmYGpKZc',
    appId: '1:1042031045023:android:88f8c78b1c500310b7b5aa',
    messagingSenderId: '1042031045023',
    projectId: 'roadsafety-f3755',
    storageBucket: 'roadsafety-f3755.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2TmkXWmLgbzxPaurKD1OtFWhaKaDgK_g',
    appId: '1:1042031045023:ios:b7dca5cfe0623f55b7b5aa',
    messagingSenderId: '1042031045023',
    projectId: 'roadsafety-f3755',
    storageBucket: 'roadsafety-f3755.appspot.com',
    iosBundleId: 'com.example.roadSafety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2TmkXWmLgbzxPaurKD1OtFWhaKaDgK_g',
    appId: '1:1042031045023:ios:354dad3aa9e83a02b7b5aa',
    messagingSenderId: '1042031045023',
    projectId: 'roadsafety-f3755',
    storageBucket: 'roadsafety-f3755.appspot.com',
    iosBundleId: 'com.example.roadSafety.RunnerTests',
  );
}
